// Auto-generated by ScriptingDefineSymbols. Do not edit.
namespace GameFrameX.Editor
{
    /// <summary>
    /// 编译触发标记文件。
    /// </summary>
    internal static class CompileTriggerStamp
    {
        internal const string Value = "2026-04-07 13:06:04.312";
    }
}
