// Auto-generated by ScriptingDefineSymbols. Do not edit.
namespace Godot.Hotfix
{
    /// <summary>
    /// 编译触发标记文件。
    /// </summary>
    internal static class CompileTriggerStamp
    {
        internal const string Value = "2026-04-14 03:06:11.927";
    }
}
